new workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -23,10 +23,10 @@ jobs:
           cache: 'npm'
 
       - name: Install dependencies
-        run: npm install npm@latest -g
+        run: npm install
 
-      - name: Check Next.js availability
-        run: npx next --version
+      - name: Check Next.js installation
+        run: npx next --version || echo "Next.js is missing!"
 
       - name: Build with Turbo
-        run: npx turbo run build
+        run: npx turbo run build --force
