add prisma generate

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -28,6 +28,9 @@ jobs:
       - name: Verify Next.js Installation
         run: npx next --version || echo "Next.js is missing!"
 
+      - name: Verify Next.js Installation
+        run: npx next --version || echo "Next.js is missing!"
+        
       - name: Build Docs Manually (Debugging)
         run: cd apps/merchant && npx next build
 
